from pydantic import BaseModel, Field
from typing import List, Dict, Optional, Any

class SensorReading(BaseModel):
    temperature: float = Field(..., description="Temperature in °C")
    vibration: float = Field(..., description="Vibration in mm/s")
    sound: float = Field(..., description="Sound level in dB")
    current: float = Field(..., description="Current consumption in A")
    timestamp: str = Field(..., description="ISO or formatted timestamp")

class MachineOverview(BaseModel):
    id: str
    name: str
    type: str
    location: str
    status: str  # "ONLINE", "OFFLINE"
    health_score: float  # 0 to 100
    condition: str  # "GOOD", "WARNING", "CRITICAL"
    operating_hours: int
    last_maintenance: str
    next_maintenance: str
    current_readings: SensorReading

class PredictionResponse(BaseModel):
    machine_id: str
    health_score: float
    failure_probability: float
    risk_level: str  # "LOW", "MEDIUM", "HIGH", "CRITICAL"
    recommended_action: str
    feature_importance: Dict[str, float]
    is_demo_model: bool = True
    disclaimer: str = "Demo ML prediction generated by Random Forest model trained on synthetic baseline dataset."

class AlertItem(BaseModel):
    id: str
    severity: str  # "CRITICAL", "WARNING", "INFO", "RESOLVED"
    timestamp: str
    machine_id: str
    machine_name: str
    sensor: str
    message: str
    status: str  # "ACTIVE", "RESOLVED"
    value: float
    threshold: float

class MaintenanceRecommendation(BaseModel):
    id: str
    machine_id: str
    machine_name: str
    sensor: str
    finding: str
    recommendation: str
    priority: str  # "High", "Medium", "Low"
    timestamp: str
    disclaimer: str = "AI demo recommendation — verify with certified engineering team before servicing."

class SettingsModel(BaseModel):
    temp_warning: float
    temp_critical: float
    vibration_warning: float
    vibration_critical: float
    sound_warning: float
    sound_critical: float
    current_warning: float
    current_critical: float
    simulation_speed: float
    demo_mode: bool

class AnomalyInjectRequest(BaseModel):
    machine_id: str
    sensor: str  # "temperature", "vibration", "sound", "current", "all"
    severity: str = "critical"  # "warning", "critical"
